spring.application.name=student_management

spring.datasource.url=jdbc:mysql://localhost:3306/StudentDB
spring.datasource.username=root
spring.datasource.password=Amit@sangeeta23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true